package com.fego.transaction.service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.fego.transaction.dto.ConsentResponseDto;
import com.fego.transaction.dto.TransactionRequestDto;
import com.fego.transaction.entity.Transaction;
import com.fego.transaction.repository.TransactionRepository;

@Service
public class TransactionService {
	private final TransactionRepository transactionRepository;
	private static final Logger log = LoggerFactory.getLogger(TransactionService.class);

	public TransactionService(TransactionRepository transactionRepository) {
		this.transactionRepository = transactionRepository;
	}

	public ConsentResponseDto save(TransactionRequestDto transactionRequestDto) {
		List<Transaction> txnList = new ArrayList<>();
		transactionRequestDto.getTxnMap().entrySet().stream().forEach(action -> {
			Transaction txn = new Transaction();
			String[] keyParts = action.getKey().split(",");
			txn.setStartDate(keyParts[1]);
			txn.setUserId(transactionRequestDto.getUserId());
			txn.setEndDate(keyParts[2]);
			txn.setAccountId(Long.valueOf(keyParts[0]));
			txn.setAmount(action.getValue().getAmount());
			txn.setCurrentBalance(action.getValue().getCurrentBalance());
			txn.setBalance(action.getValue().getBalance());
			txn.setMode(action.getValue().getMode());
			txn.setNarration(action.getValue().getNarration());
			txn.setReference(action.getValue().getReference());
			txn.setTransactionTimestamp(action.getValue().getTransactionTimestamp());
			txn.setTxnId(action.getValue().getTxnId());
			txn.setType(action.getValue().getType());
			txn.setValueDate(action.getValue().getValueDate());
			txn.setTransactionDateTime(action.getValue().getTransactionDateTime());
			txn.setAmc(action.getValue().getAmc());
			txn.setRegistrar(action.getValue().getRegistrar());
			txn.setSchemeCode(action.getValue().getSchemeCode());
			txn.setSchemePlan(action.getValue().getSchemePlan());
			txn.setSchemeTypes(action.getValue().getSchemeTypes());
			txn.setSchemeCategory(action.getValue().getSchemeCategory());
			txn.setIsin(action.getValue().getIsin());
			txn.setAmfiCode(action.getValue().getAmfiCode());
			txn.setSchemeOption(action.getValue().getSchemeOption());
			txn.setFundType(action.getValue().getFundType());
			txn.setUcc(action.getValue().getUcc());
			txn.setClosingUnits(action.getValue().getClosingUnits());
			txn.setLienUnits(action.getValue().getLienUnits());
			txn.setNav(action.getValue().getNav());
			txn.setNavDate(action.getValue().getNavDate());
			txn.setOrderDate(action.getValue().getOrderDate());
			txn.setExecutionDate(action.getValue().getExecutionDate());
			txn.setLockInDays(action.getValue().getLockinDays());
			txn.setLockInFlag(action.getValue().getLockinFlag());
			txn.setCost(action.getValue().getCost());
			txn.setPremium(action.getValue().getPremium());
			txn.setPremiumAllocationCharge(action.getValue().getPremiumAllocationCharge());
			txn.setOtherCharges(action.getValue().getOtherCharges());
			txn.setUnits(action.getValue().getUnits());
			txn.setFundName(action.getValue().getFundName());
			txn.setTxnDate(action.getValue().getTxnDate());
			txn.setEmployeeDepositAmount(action.getValue().getEmployeeDepositAmount());
			txn.setEmployerDepositAmount(action.getValue().getEmployerDepositAmount());
			txn.setEmployeeWithdrawalAmount(action.getValue().getEmployeeWithdrawalAmount());
			txn.setEmployerWithdrawalAmount(action.getValue().getEmployerWithdrawalAmount());
			txn.setPensionFundAmount(action.getValue().getPensionFundAmount());
			txn.setTxnType(action.getValue().getTxnType());
			txn.setStatementDate(action.getValue().getStatementDate());
			txn.setMcc(action.getValue().getMcc());
			txn.setMaskedCardNumber(action.getValue().getMaskedCardNumber());
			txn.setIssuerName(action.getValue().getIssuerName());
			txn.setSymbol(action.getValue().getSymbol());
			txn.setExchange(action.getValue().getExchange());
			txn.setTransactionDescription(action.getValue().getTransactionDescription());
			txn.setPrice(action.getValue().getPrice());
			txn.setUnitsType(action.getValue().getUnitsType());
			txn.setNumUnitsTransacted(action.getValue().getNumUnitsTransacted());
			txn.setTradeValue(action.getValue().getTradeValue());
			txn.setTotalCharge(action.getValue().getTotalCharge());
			txn.setNameOfAsset(action.getValue().getNameofAsset());
			txn.setInvestmentDateTime(action.getValue().getInvestmentDateTime());
			txn.setInvestmentValue(action.getValue().getInvestmentValue());
			txn.setRedemptionDate(action.getValue().getRedemptionDate());
			txn.setRedemptionValue(action.getValue().getRedemptionValue());
			txn.setFundFeesPaymentDate(action.getValue().getFundFeesPaymentDate());
			txn.setFundFeesPaymentAmount(action.getValue().getFundFeesPaymentAmount());
			txn.setReInvestmentDate(action.getValue().getReInvestmentDate());
			txn.setReInvestmentValue(action.getValue().getReInvestmentValue());
			txn.setPaymentInvestorDate(action.getValue().getPaymentInvestorDate());
			txn.setPaymentInvestorAmount(action.getValue().getPaymentInvestorAmount());
			txn.setTaxPaidDate(action.getValue().getTaxPaidDate());
			txn.setTaxPaidValue(action.getValue().getTaxPaidValue());
			txn.setDividendType(action.getValue().getDividendType());
			txn.setOrderId(action.getValue().getOrderId());
			txn.setTradeId(action.getValue().getTradeId());
			txn.setCompanyName(action.getValue().getCompanyName());
			txn.setRate(action.getValue().getRate());
			txn.setSchemeName(action.getValue().getSchemeName());
			txn.setDpId(action.getValue().getDpId());
			txn.setSchemeMinLotSize(action.getValue().getSchemeMinLotSize());
			txn.setFaceValueofUnits(action.getValue().getFaceValueofUnits());
			txn.setBrokerCode(action.getValue().getBrokerCode());
			txn.setCurrency(action.getValue().getCurrency());
			txn.setOtherTaxes(action.getValue().getOtherTaxes());
			txn.setEquityCategory(action.getValue().getEquityCategory());
			txn.setInstrumentType(action.getValue().getInstrumentType());
			txn.setOptionType(action.getValue().getOptionType());
			txn.setStrikePrice(action.getValue().getStrikePrice());
			txn.setShareHolderEquityType(action.getValue().getShareHolderEquityType());
			txn.setStt(action.getValue().getStt());
			txn.setScheme(action.getValue().getScheme());
			txn.setFolioNo(action.getValue().getFolioNo());
			txn.setCreatedAt(LocalDateTime.now());
			txn.setUpdatedAt(LocalDateTime.now());
			txn.setCreatedBy(transactionRequestDto.getUserId());
			txn.setUpdatedBy(transactionRequestDto.getUserId());
			txnList.add(txn);
		});
		transactionRequestDto.getTxnListMap().entrySet().stream().forEach(action -> {
			action.getValue().stream().forEach(transaction -> {
				Transaction txn = new Transaction();
				String[] keyParts = action.getKey().split(",");
				txn.setStartDate(keyParts[1]);
				txn.setEndDate(keyParts[2]);
				txn.setAccountId(Long.valueOf(keyParts[0]));
				txn.setUserId(transactionRequestDto.getUserId());
				txn.setAmount(transaction.getAmount());
				txn.setCurrentBalance(transaction.getCurrentBalance());
				txn.setBalance(transaction.getBalance());
				txn.setMode(transaction.getMode());
				txn.setNarration(transaction.getNarration());
				txn.setReference(transaction.getReference());
				txn.setTransactionTimestamp(transaction.getTransactionTimestamp());
				txn.setTxnId(transaction.getTxnId());
				txn.setType(transaction.getType());
				txn.setValueDate(transaction.getValueDate());
				txn.setTransactionDateTime(transaction.getTransactionDateTime());
				txn.setAmc(transaction.getAmc());
				txn.setRegistrar(transaction.getRegistrar());
				txn.setSchemeCode(transaction.getSchemeCode());
				txn.setSchemePlan(transaction.getSchemePlan());
				txn.setSchemeTypes(transaction.getSchemeTypes());
				txn.setSchemeCategory(transaction.getSchemeCategory());
				txn.setIsin(transaction.getIsin());
				txn.setAmfiCode(transaction.getAmfiCode());
				txn.setSchemeOption(transaction.getSchemeOption());
				txn.setFundType(transaction.getFundType());
				txn.setUcc(transaction.getUcc());
				txn.setClosingUnits(transaction.getClosingUnits());
				txn.setLienUnits(transaction.getLienUnits());
				txn.setNav(transaction.getNav());
				txn.setNavDate(transaction.getNavDate());
				txn.setOrderDate(transaction.getOrderDate());
				txn.setExecutionDate(transaction.getExecutionDate());
				txn.setLockInDays(transaction.getLockinDays());
				txn.setLockInFlag(transaction.getLockinFlag());
				txn.setCost(transaction.getCost());
				txn.setPremium(transaction.getPremium());
				txn.setPremiumAllocationCharge(transaction.getPremiumAllocationCharge());
				txn.setOtherCharges(transaction.getOtherCharges());
				txn.setUnits(transaction.getUnits());
				txn.setFundName(transaction.getFundName());
				txn.setTxnDate(transaction.getTxnDate());
				txn.setEmployeeDepositAmount(transaction.getEmployeeDepositAmount());
				txn.setEmployerDepositAmount(transaction.getEmployerDepositAmount());
				txn.setEmployeeWithdrawalAmount(transaction.getEmployeeWithdrawalAmount());
				txn.setEmployerWithdrawalAmount(transaction.getEmployerWithdrawalAmount());
				txn.setPensionFundAmount(transaction.getPensionFundAmount());
				txn.setTxnType(transaction.getTxnType());
				txn.setStatementDate(transaction.getStatementDate());
				txn.setMcc(transaction.getMcc());
				txn.setMaskedCardNumber(transaction.getMaskedCardNumber());
				txn.setIssuerName(transaction.getIssuerName());
				txn.setSymbol(transaction.getSymbol());
				txn.setExchange(transaction.getExchange());
				txn.setTransactionDescription(transaction.getTransactionDescription());
				txn.setPrice(transaction.getPrice());
				txn.setUnitsType(transaction.getUnitsType());
				txn.setNumUnitsTransacted(transaction.getNumUnitsTransacted());
				txn.setTradeValue(transaction.getTradeValue());
				txn.setTotalCharge(transaction.getTotalCharge());
				txn.setNameOfAsset(transaction.getNameofAsset());
				txn.setInvestmentDateTime(transaction.getInvestmentDateTime());
				txn.setInvestmentValue(transaction.getInvestmentValue());
				txn.setRedemptionDate(transaction.getRedemptionDate());
				txn.setRedemptionValue(transaction.getRedemptionValue());
				txn.setFundFeesPaymentDate(transaction.getFundFeesPaymentDate());
				txn.setFundFeesPaymentAmount(transaction.getFundFeesPaymentAmount());
				txn.setReInvestmentDate(transaction.getReInvestmentDate());
				txn.setReInvestmentValue(transaction.getReInvestmentValue());
				txn.setPaymentInvestorDate(transaction.getPaymentInvestorDate());
				txn.setPaymentInvestorAmount(transaction.getPaymentInvestorAmount());
				txn.setTaxPaidDate(transaction.getTaxPaidDate());
				txn.setTaxPaidValue(transaction.getTaxPaidValue());
				txn.setDividendType(transaction.getDividendType());
				txn.setOrderId(transaction.getOrderId());
				txn.setTradeId(transaction.getTradeId());
				txn.setCompanyName(transaction.getCompanyName());
				txn.setRate(transaction.getRate());
				txn.setSchemeName(transaction.getSchemeName());
				txn.setDpId(transaction.getDpId());
				txn.setSchemeMinLotSize(transaction.getSchemeMinLotSize());
				txn.setFaceValueofUnits(transaction.getFaceValueofUnits());
				txn.setBrokerCode(transaction.getBrokerCode());
				txn.setCurrency(transaction.getCurrency());
				txn.setOtherTaxes(transaction.getOtherTaxes());
				txn.setEquityCategory(transaction.getEquityCategory());
				txn.setInstrumentType(transaction.getInstrumentType());
				txn.setOptionType(transaction.getOptionType());
				txn.setStrikePrice(transaction.getStrikePrice());
				txn.setShareHolderEquityType(transaction.getShareHolderEquityType());
				txn.setStt(transaction.getStt());
				txn.setScheme(transaction.getScheme());
				txn.setFolioNo(transaction.getFolioNo());
				txn.setCreatedAt(LocalDateTime.now());
				txn.setUpdatedAt(LocalDateTime.now());
				txn.setCreatedBy(transactionRequestDto.getUserId());
				txn.setUpdatedBy(transactionRequestDto.getUserId());
				txnList.add(txn);
			});
		});
		transactionRepository.saveAll(txnList);
		log.info("Transaction details are saved into the table.");
		ConsentResponseDto consentResponseDto = new ConsentResponseDto();
		consentResponseDto.setStatus("SUCCESS");
		return consentResponseDto;
	}
}